<?php 
/********************************************************************************
*********************************************************************************
// XML to call WebService for "IDA"
*********************************************************************************
********************************************************************************/
$xmlSend_ida='<x:Envelope xmlns:x="http://schemas.xmlsoap.org/soap/envelope/" xmlns:pre="http://www.correos.es/iris6/services/preregistroetiquetas">
    <x:Header/>
    <x:Body>
        <pre:PeticionPreRegistroIdaVta>
            <pre:FechaOperacion>'.$currentdate.'</pre:FechaOperacion>
            <pre:CodEtiquetador>'.$correoetiquetadora.'</pre:CodEtiquetador>
            <pre:NumContrato>'.$numcontrato.'</pre:NumContrato>
            <pre:NumCliente>'.$numcliente.'</pre:NumCliente>
            <pre:Care>000000</pre:Care>
            <pre:TotalBultos>1</pre:TotalBultos>
            <pre:ModDevEtiqueta>2</pre:ModDevEtiqueta>
            <pre:Remitente>
                <pre:Identificacion>
                    <pre:Nombre>'.$nombre_remitente.'</pre:Nombre>
                    <pre:Apellido1>'.$apellido1_remitente.'</pre:Apellido1>
                    <pre:Apellido2>'.$apellido2_remitente.'</pre:Apellido2>
                    <pre:Nif>'.$nif_remitente.'</pre:Nif>
                    <pre:Empresa>'.$empresa_remitente.'</pre:Empresa>
                    <pre:PersonaContacto>'.$contacto_remitente.'</pre:PersonaContacto>
                </pre:Identificacion>
                <pre:DatosDireccion>
                    <pre:TipoDireccion>?</pre:TipoDireccion>
                    <pre:Direccion>'.$direccion_remitente.'</pre:Direccion>
                    <pre:Numero></pre:Numero>
                    <pre:Portal></pre:Portal>
                    <pre:Bloque></pre:Bloque>
                    <pre:Escalera></pre:Escalera>
                    <pre:Piso></pre:Piso>
                    <pre:Puerta></pre:Puerta>
                    <pre:Localidad>'.$localidad_remitente.'</pre:Localidad>
                    <pre:Provincia>'.$provincia_remitente.'</pre:Provincia>
                </pre:DatosDireccion>
                <pre:CP>'.$cp_remitente.'</pre:CP>
                <pre:Telefonocontacto>'.$telefono_remitente.'</pre:Telefonocontacto>
                <pre:Email>'.$email_remitente.'</pre:Email>
                <pre:DatosSMS>
                    <pre:NumeroSMS>?</pre:NumeroSMS>
                    <pre:Idioma>1</pre:Idioma>
                </pre:DatosSMS>
            </pre:Remitente>
            <pre:Destinatario>
                <pre:Identificacion>
                    <pre:Nombre>'.$nombre_destinatario.'</pre:Nombre>
                    <pre:Apellido1>'.$apellido1_destinatario.'</pre:Apellido1>
                    <pre:Apellido2>'.$apellido2_destinatario.'</pre:Apellido2>
                    <pre:Nif>'.$nif_destinatario.'</pre:Nif>
                    <pre:Empresa>'.$empresa_destinatario.'</pre:Empresa>
                    <pre:PersonaContacto>'.$nombre_destinatario.'</pre:PersonaContacto>
                </pre:Identificacion>
                <pre:DatosDireccion>
                    <pre:TipoDireccion>?</pre:TipoDireccion>
                    <pre:Direccion>'.$direccion_destinatario.'</pre:Direccion>
                    <pre:Numero></pre:Numero>
                    <pre:Portal></pre:Portal>
                    <pre:Bloque></pre:Bloque>
                    <pre:Escalera></pre:Escalera>
                    <pre:Piso></pre:Piso>
                    <pre:Puerta></pre:Puerta>
                    <pre:Localidad>'.$localidad_destinatario.'</pre:Localidad>
                    <pre:Provincia>'.$provincia_destinatario.'</pre:Provincia>
                </pre:DatosDireccion>
                <pre:CP>'.$cp_destinatario.'</pre:CP>
                <pre:Pais>España</pre:Pais>
                <pre:Telefonocontacto>'.$telefono_destinatario.'</pre:Telefonocontacto>
                <pre:Email>'.$email_destinatario.'</pre:Email>
            </pre:Destinatario>
            <pre:Envio>
                <pre:NumBulto>1</pre:NumBulto>
                <pre:CodProducto>'.$codigo_producto.'</pre:CodProducto>
                <pre:ReferenciaCliente></pre:ReferenciaCliente>
                <pre:ReferenciaCliente2></pre:ReferenciaCliente2>
                <pre:TipoFranqueo>FP</pre:TipoFranqueo>
                <ModalidadEntrega>ST</ModalidadEntrega>
                <pre:Pesos>
                    <pre:Peso>
                        <pre:TipoPeso>R</pre:TipoPeso>
                        <pre:Valor>500</pre:Valor>
                    </pre:Peso>
                </pre:Pesos>
                <pre:ExisteEnvioVueltaLI>S</pre:ExisteEnvioVueltaLI>
                <pre:Observaciones1>'.$codigo_analisis.'</pre:Observaciones1>
                <pre:Observaciones2>Ida para PEGAR y vuelta para METER en el sobre</pre:Observaciones2>
            </pre:Envio>
        </pre:PeticionPreRegistroIdaVta>
    </x:Body>
</x:Envelope>';
 ?>

<!-- <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns="http://www.correos.es/iris6/services/preregistroetiquetas">
<soapenv:Header/>
    <soapenv:Body>
        <PreregistroEnvio>
            <fechaOperacion>{$smarty.now|date_format:"%d-%m-%Y %H:%M:%S"|escape:'html':'UTF-8'}</fechaOperacion>
            <CodEtiquetador>{$correos_config.correos_key|escape:'html':'UTF-8'}</CodEtiquetador>
            <ModDevEtiqueta>2</ModDevEtiqueta>
            <Care>000000</Care>
            <TotalBultos>1</TotalBultos>
            <Remitente>
                <Identificacion>
                    <Nombre>{$shipping_val.sender_firstname|escape:'html':'UTF-8'}</Nombre>
                    <Apellido1>{$shipping_val.sender_lastname1|escape:'html':'UTF-8'}</Apellido1>
                    <Apellido2>{$shipping_val.sender_lastname2|escape:'html':'UTF-8'}</Apellido2>
                    <Nif>{$shipping_val.sender_dni|escape:'html':'UTF-8'}</Nif>
                    <Empresa>{$shipping_val.sender_company|escape:'html':'UTF-8'}</Empresa>
                    <PersonaContacto>{$shipping_val.sender_contact_person|escape:'html':'UTF-8'}</PersonaContacto>
                </Identificacion>
                <DatosDireccion>
                    <Direccion>{$shipping_val.sender_address|escape:'html':'UTF-8'}</Direccion>
                    <Localidad>{$shipping_val.sender_city|escape:'html':'UTF-8'}</Localidad>
                    <Provincia>{$shipping_val.sender_state|escape:'html':'UTF-8'}</Provincia>
                </DatosDireccion>
                <CP>{$shipping_val.sender_cp|escape:'html':'UTF-8'}</CP>
                <Telefonocontacto>{$shipping_val.sender_phone|escape:'html':'UTF-8'}</Telefonocontacto>
                <Email>{$shipping_val.sender_email|escape:'html':'UTF-8'}</Email>
                <DatosSMS>
                    <NumeroSMS>{$shipping_val.sender_mobile|escape:'html':'UTF-8'}</NumeroSMS>
                    <Idioma>1</Idioma>
                </DatosSMS>
            </Remitente> 
            <Destinatario> 
                <Identificacion> 
                    {if empty($shipping_val.customer_company)}
                    <Nombre>{$shipping_val.customer_firstname|escape:'html':'UTF-8'}</Nombre>
                    <Apellido1>{$shipping_val.customer_lastname1|escape:'html':'UTF-8'}</Apellido1>
                    <Apellido2>{$shipping_val.customer_lastname2|escape:'html':'UTF-8'}</Apellido2>
                    {/if}
                    {if !empty($shipping_val.customer_company)}
                    <Empresa>{$shipping_val.customer_company|escape:'html':'UTF-8'}</Empresa>
                    <PersonaContacto>{$shipping_val.customer_firstname|escape:'html':'UTF-8'} {$shipping_val.customer_lastname1|escape:'html':'UTF-8'} {$shipping_val.customer_lastname2|escape:'html':'UTF-8'}</PersonaContacto>
                    {/if}
                </Identificacion>
                <DatosDireccion>
                    <Direccion>{$shipping_val.delivery_address|escape:'html':'UTF-8'}</Direccion>
                    <Localidad>{$shipping_val.delivery_city|escape:'html':'UTF-8'}</Localidad>
                    <Provincia>{$shipping_val.delivery_state|escape:'html':'UTF-8'}</Provincia>
                </DatosDireccion>
                <CP>{$shipping_val.delivery_postcode|escape:'html':'UTF-8'}</CP>
                <ZIP>{$shipping_val.delivery_zip|escape:'html':'UTF-8'}</ZIP>
                <Pais>{$shipping_val.country_iso|escape:'html':'UTF-8'}</Pais>
                <Telefonocontacto>{$shipping_val.phone|escape:'html':'UTF-8'}</Telefonocontacto>
                <Email>{$shipping_val.email|escape:'html':'UTF-8'}</Email>
                <DatosSMS>
                    <NumeroSMS>{$shipping_val.mobile|escape:'html':'UTF-8'}</NumeroSMS>
                    <Idioma>{$shipping_val.mobile_lang|escape:'html':'UTF-8'}</Idioma>
                </DatosSMS>
            </Destinatario> 
            <Envio>
                <CodProducto>{$carrier_code|escape:'html':'UTF-8'}</CodProducto>
                <ReferenciaCliente>{$shipping_val.order_reference|escape:'html':'UTF-8'}</ReferenciaCliente>
                <TipoFranqueo>FP</TipoFranqueo>
                <ModalidadEntrega>{$shipping_val.delivery_mode|escape:'html':'UTF-8'}</ModalidadEntrega>
                <OficinaElegida>{$shipping_val.id_office|escape:'html':'UTF-8'}</OficinaElegida>
                <Pesos>
                    <Peso>
                        <TipoPeso>R</TipoPeso>
                        <Valor>{$shipping_val.weight|escape:'html':'UTF-8'}</Valor>
                    </Peso>
                </Pesos>
                <Largo>{$shipping_val.long|escape:'html':'UTF-8'}</Largo>
                <Alto>{$shipping_val.height|escape:'html':'UTF-8'}</Alto>
                <Ancho>{$shipping_val.width|escape:'html':'UTF-8'}</Ancho>
                <ValoresAnadidos>
                    <ImporteSeguro>{$shipping_val.insurance_value|escape:'html':'UTF-8'}</ImporteSeguro>
                    <Reembolso> 
                        <TipoReembolso>{$shipping_val.cashondelivery_type|escape:'html':'UTF-8'}</TipoReembolso>
                        <Importe>{$shipping_val.cashondelivery_value|escape:'html':'UTF-8'}</Importe>
                        <NumeroCuenta>{$shipping_val.cashondelivery_bankac|escape:'html':'UTF-8'}</NumeroCuenta>
                    </Reembolso>
                    <FranjaHorariaConcertada>{$shipping_val.id_schedule|escape:'html':'UTF-8'}</FranjaHorariaConcertada>
                </ValoresAnadidos>
                <Aduana>
                    <TipoEnvio>{$shipping_val.customs_type|escape:'html':'UTF-8'}</TipoEnvio>
                    <DescAduanera>
                        <DATOSADUANA>
                            <Cantidad>{$shipping_val.customs_product_qty|escape:'html':'UTF-8'}</Cantidad>
                            <Descripcion>{$shipping_val.customs_description|escape:'html':'UTF-8'}</Descripcion>
                            <Pesoneto>{$shipping_val.customs_product_weight|escape:'html':'UTF-8'}</Pesoneto>
                            <Valorneto>{$shipping_val.customs_product_value|escape:'html':'UTF-8'}</Valorneto>
                        </DATOSADUANA>
                    </DescAduanera>
                </Aduana>
                <Observaciones1>{$shipping_val.observations|escape:'html':'UTF-8'}</Observaciones1>
                <Observaciones2>{$shipping_val.delivery_address2|escape:'html':'UTF-8'}</Observaciones2>
                <AdmisionHomepaq>{$shipping_val.homepaq_admission|escape:'html':'UTF-8'}</AdmisionHomepaq>
                <CodigoHomepaq>{$shipping_val.homepaq_code|escape:'html':'UTF-8'}</CodigoHomepaq>
                <ToquenIdCorPaq>{$shipping_val.homepaq_token|escape:'html':'UTF-8'}</ToquenIdCorPaq>
                <InstruccionesDevolucion>D</InstruccionesDevolucion>
            </Envio>
        </PreregistroEnvio>
    </soapenv:Body>
</soapenv:Envelope> -->